#!/bin/bash
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

SCRIPT_DIR=`realpath \`dirname $0\``

export DEBIAN_FRONTEND=noninteractive

function installApp() {
  APP=$1
  INST=$2
  if [ "$INST" == "" ]; then INST=$APP; fi
  type $APP >& /dev/null
  RC=$?; if [ "$RC" == "0" ]; then
      echo -e "${SCRIPT}:" `type $APP` "[OK]"
  else
      echo -e "${SCRIPT}: installing $APP ... (sudo)"
      sudo apt-get install -y $INST
  fi
}

installApp opusenc opus-tools
installApp ffmpeg

