#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

echo -e "${SCRIPT}: BEGIN `date` (OK)"

echo -e "${SCRIPT}: apt update; apt upgrade..."
sudo apt-get update -y
sudo apt-get upgrade -y

# HACK BEGIN
# FIX BROKEN INSTALL OF  grub-efi-amd64-signed
sudo rm /var/lib/dpkg/info/grub*
sudo dpkg --configure -a
# HACK END

${DIR}/install-node16 &&
${DIR}/update-npm &&
${DIR}/install-ripgrep &&
${DIR}/install-audio-tools &&
npm install && 
echo -e "${SCRIPT}: END `date` (OK)"
