#!/bin/bash
DIR=`dirname $0`; 
pushd $DIR/..
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
echo -e "${SCRIPT}: BEGIN `date`"

git pull
npm install --save scv-bilara@latest

npm run test; RC=$?; 
if [ "$RC" != "0" ]; then
  echo ERROR $RC
  exit $RC
fi

$DIR/publish-npm

echo -e "${SCRIPT}: END `date`"
