#!/bin/bash
DIR=`dirname $0`; 
pushd $DIR/..
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
echo -e "${SCRIPT}: BEGIN `date`"

set -e

git pull
echo -e "${SCRIPT}: updating dependencies..."
npm install --save scv-bilara@latest\
  vuetify@next\
  just-simple@latest\
  memo-again@latest\
  say-again@latest\
  suttacentral-api@latest\
  oya-ann@latest

CMD="git status | grep 'nothing to commit' > /dev/null"
if bash -c "$CMD"; then
  echo "$SCRIPT: Nothing to commit (OK)"
  exit 0
fi

echo -e "$SCRIPT: updated package dependencies"
git commit -am "$SCRIPT: updated package dependencies"
VERSION=`npm version patch`
echo -e "$SCRIPT: committing package version ${VERSION}"
git push

echo -e "$SCRIPT: updating Dockerhub..."
npm run build:dist
npm run ghpages
npm run build:dockerhub

#TODO: solve github action AWS credential challenge
#npm run test; RC=$?; 
#if [ "$RC" == "0" ]; then
#  echo TEST COMPLETED!
#else 
#  echo "TESTS FAILED (RC$RC)"
#  exit $RC
#fi

echo -e "${SCRIPT}: END `date`"
