#!/bin/bash

DIR=`dirname $0`; 
pushd $DIR/.. > /dev/null
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
echo -e "${SCRIPT}: BEGIN `date`"

cd $DIR/..

mkdir -p local
cd local
if [ -e ebt-data ]; then
  echo "$SCRIPT: git pull ebt-data"
  cd ebt-data
  git pull; RC=$? || exit $RC
else 
  echo "$SCRIPT: git clone ebt-data"
  git clone https://git@github.com/ebt-site/ebt-data; RC=$? || exit $RC
fi

echo -e "${SCRIPT}: END `date`"
